---
- name: Install openvpn.
  apt:
    name: openvpn
    state: present

- name: Install configuration file from data.
  copy:
    src: "{{ role_path }}/files/client.ovpn"
    dest: "/etc/openvpn/client/client.conf"
    mode: 0600
