---
- name: Install keepassxc package.
  apt:
    name: keepassxc
    state: present

- name: Create keepassxc db directory.
  become: no
  file:
    path: "{{ home_dir }}/keepassxc"
    state: directory
    mode: 0750

- name: Configure file kdbx.
  become: no
  copy:
    src: "{{ role_path }}/files/caibar.kdbx"
    dest: "{{ home_dir }}/keepassxc/caibar.kdbx"
    mode: 0664
