---
- name: Configure the Oracle APT key.
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: Configure the VirtualBox APT repositories.
  apt_repository:
    repo: "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present

- name: Install VirtualBox {{ virtualbox_version }}.
  apt:
    pkg: virtualbox-{{ virtualbox_version }}
    state: present
    update_cache: yes

- name: Ensure recommended packages are installed.
  apt:
    name: dkms
    state: present
    update_cache: yes
