---
- name: Check current docker-compose version.
  command: docker-compose --version
  register: _docker_compose_current_version
  changed_when: no
  failed_when: no

- name: Delete existing docker-compose version if it's different.
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    _docker_compose_current_version.stdout is defined
    and docker_compose_version not in _docker_compose_current_version.stdout

- name: Install Docker Compose.
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: 0755
