---
- name: Add gpg Google linux signing key.
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: Apt Google chrome repository.
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
    state: present
    update_cache: yes

- name: Install Google chrome latest version.
  apt:
    name: google-chrome-stable
    state: present
